server:
  port: 8082
spring:
  application:
    name: "Mensajeria"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    url: "http://localhost:8082"
twilio:
  account-sid: "${TWILIO_ACCOUNT_SID:ACa319f4a1df19bb25ddb3d9757cb4d2a2}"
  auth-token: "${TWILIO_AUTH_TOKEN:50734d3a3f06ad5cade27107f040eee2}"
  from-number: "${TWILIO_FROM_NUMBER:+19787651656}"
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      twilioSms:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "5s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: "30s"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"
